name: EasyKits
main: info.TrenTech.EasyKits.EasyKits
version: 1.4.9
commands:
  kit:
    usage: /<command>
    aliases: [easykits,k]
permissions:
  EasyKits.*:
    default: op
    children:
      EasyKits.cmd.*: true
      EastKits.kits.*: true
  EasyKits.cmd.*:
    default: op
    children:     
      EasyKits.cmd.reload: true
      EasyKits.cmd.create: true
      EasyKits.cmd.remove: true
      EasyKits.cmd.give: true
      EasyKits.cmd.list: true
      EasyKits.cmd.show: true
      EasyKits.cmd.update: true
  EasyKits.cmd.reload:
    default: op
  EasyKits.cmd.create:
    default: op
  EasyKits.cmd.remove:
    default: op
  EasyKits.cmd.give:
    default: op
  EasyKits.cmd.list:
    default: op
  EasyKits.cmd.show:
    default: op
  EasyKits.cmd.update:
    default: op
  EasyKits.kits.*:
    default: op
  EasyKits.kits.cooldown:
    default: false
  EasyKits.kits.maxuse:
    default: false
  EasyKits.kits.bypassprice:
    default: op
  EasyKits.sign:
    default: op